# Generated by Django 2.2 on 2019-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(max_length=250, null=True, verbose_name='Адрес')),
                ('instagram', models.CharField(max_length=250, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(max_length=250, null=True, verbose_name='Facebook')),
                ('m_phone', models.CharField(max_length=30, null=True, verbose_name='Номер телефона')),
            ],
        ),
    ]
